name: stable-check

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: moon version
        run: |
          moon version --all
          moonrun --version
      - name: check
        run: moon check --deny-warn --target all
      - name: moon info
        run: |
          moon info --target wasm,wasm-gc,js,native
          git diff --exit-code
      - name: format diff
        run: |
          moon fmt
          git diff --exit-code
      - name: Set ulimit and run moon test
        run: |
          ulimit -s 8176
          moon test --target all
